# Test goal: newest GCC with OpenCL
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   Compiler: GCC newest supported
#   GPU: OpenCL
#   FFT: CLFFT
#   HW: None, previously AMD GPU, see #4745
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 22.04
#   Build type: Debug
#   Compiler: GCC 12
#   MPI: thread_MPI
#   SIMD: AVX_512
#   Parallelism nt/ntomp: 4/2 (unit tests)
#   Parallelism nt/ntomp: 2/1 (regression tests)

gromacs:gcc-12:configure:
  extends:
    - .gromacs:base:configure
    - .use-gcc:base
    - .use-opencl
    - .rules:merge-and-post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-12-rocm-5.4.1
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=AVX_512"
    CMAKE_EXTRA_OPTIONS: "-DGMX_EXTERNAL_CLFFT=ON"
    COMPILER_MAJOR_VERSION: 12

gromacs:gcc-12:build:
  extends:
    - .gromacs:base:build
    - .before_script:default
    - .use-ccache
    - .rules:merge-and-post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-12-rocm-5.4.1
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
  needs:
    - job: gromacs:gcc-12:configure

gromacs:gcc-12:test:
  extends:
    - .gromacs:base:test
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-12-rocm-5.4.1
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    # GPUs disabled! See #4745
    #LD_LIBRARY_PATH: "/opt/rocm/opencl/lib"
    #ROC_ENABLE_PRE_VEGA: 1
    #GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
    #GMX_FORCE_UPDATE_DEFAULT_CPU: 1
    #GPU_VENDOR: "AMD"
    #GPU_COUNT: 1
  needs:
    - job: gromacs:gcc-12:build

gromacs:gcc-12:regressiontest:
  extends:
    - .gromacs:base:regressiontest
  rules:
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-12-rocm-5.4.1
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    # GPUs disabled! See #4745
    #LD_LIBRARY_PATH: "/opt/rocm/opencl/lib"
    #ROC_ENABLE_PRE_VEGA: 1
    REGRESSIONTEST_PME_RANK_NUMBER: 0
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 2
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
    #GPU_VENDOR: "AMD"
    #GPU_COUNT: 1
  needs:
    - job: gromacs:gcc-12:build
    - job: regressiontests:prepare

